// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigurationFile() {
  return window['go']['main']['App']['GetConfigurationFile']();
}

export function GetFlowsOfIntegrationPackage(arg1) {
  return window['go']['main']['App']['GetFlowsOfIntegrationPackage'](arg1);
}

export function GetIntegrationPackages(arg1) {
  return window['go']['main']['App']['GetIntegrationPackages'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InspectFlow(arg1) {
  return window['go']['main']['App']['InspectFlow'](arg1);
}

export function SaveConfigurationFile(arg1) {
  return window['go']['main']['App']['SaveConfigurationFile'](arg1);
}

export function SetTenantKey(arg1) {
  return window['go']['main']['App']['SetTenantKey'](arg1);
}

export function TransportFlow(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TransportFlow'](arg1, arg2, arg3, arg4, arg5);
}
