// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {model} from '../models';
import {main} from '../models';

export function GetConfigurationFile():Promise<config.ConfigurationFile>;

export function GetFlowsOfIntegrationPackage(arg1:string):Promise<Array<model.IntegrationFlow>>;

export function GetIntegrationPackages(arg1:string):Promise<Array<model.IntegrationPackage>>;

export function Greet(arg1:main.Person):Promise<string>;

export function InspectFlow(arg1:string):Promise<model.IntegrationFlow>;

export function SaveConfigurationFile(arg1:config.ConfigurationFile):Promise<void>;

export function SetTenantKey(arg1:string):Promise<void>;

export function TransportFlow(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;
