// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';

export function GetFlowsOfIntegrationPackage(arg1:string):Promise<Array<model.IntegrationFlow>>;

export function GetIntegrationPackages():Promise<Array<model.IntegrationPackage>>;

export function Greet(arg1:main.Person):Promise<string>;

export function InspectFlow(arg1:string):Promise<model.IntegrationFlow>;

export function TransportFlow(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;
