// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFlowsOfIntegrationPackage(arg1) {
  return window['go']['main']['App']['GetFlowsOfIntegrationPackage'](arg1);
}

export function GetIntegrationPackages() {
  return window['go']['main']['App']['GetIntegrationPackages']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InspectFlow(arg1) {
  return window['go']['main']['App']['InspectFlow'](arg1);
}

export function TransportFlow(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TransportFlow'](arg1, arg2, arg3, arg4, arg5);
}
